// <auto-generated />
using Avatar_Challenge.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Avatar_Challenge.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250216110208_avatar to speciality relationship")]
    partial class avatartospecialityrelationship
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Avatar_Challenge.Models.AvatarModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AvatarName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullNames")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RegistrationNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SpecialityId")
                        .HasColumnType("int");

                    b.Property<int?>("SpecialityModelId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SpecialityModelId");

                    b.ToTable("Avatars");
                });

            modelBuilder.Entity("Avatar_Challenge.Models.SpecialityModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.HasKey("Id");

                    b.ToTable("SpecialityModel");
                });

            modelBuilder.Entity("Avatar_Challenge.Models.AvatarModel", b =>
                {
                    b.HasOne("Avatar_Challenge.Models.SpecialityModel", "SpecialityModel")
                        .WithMany("Avatars")
                        .HasForeignKey("SpecialityModelId");

                    b.Navigation("SpecialityModel");
                });

            modelBuilder.Entity("Avatar_Challenge.Models.SpecialityModel", b =>
                {
                    b.Navigation("Avatars");
                });
#pragma warning restore 612, 618
        }
    }
}
